"""CMS/LMS context profiles extracted and normalized from the provided topic document and Moodle wordlist."""

PROFILES = {
    "wordpress": {
        "signals": {
            "headers": ["x-powered-by: php"],
            "body": [
                "/wp-content/",
                "/wp-includes/",
                "wp-json",
                'generator" content="wordpress',
            ],
            "cookies": [],
            "probe_paths": ["/wp-json/", "/wp-login.php", "/readme.html"],
        },
        "paths": [
            "/wp-admin/",
            "/wp-includes/",
            "/wp-content/",
            "/wp-content/uploads/",
            "/wp-content/plugins/akismet/",
            "/wp-content/plugins/contact-form-7/",
            "/wp-content/plugins/woocommerce/",
            "/wp-content/plugins/wp-file-manager/",
            "/wp-content/plugins/mailpoet/",
            "/wp-content/plugins/revslider/",
            "/wp-content/plugins/elementor/",
            "/wp-content/themes/twentytwentyone/",
            "/wp-content/themes/twentytwentythree/",
            "/wp-content/themes/astra/",
            "/wp-content/themes/oceanwp/",
            "/wp-content/themes/divi/",
            "/readme.html",
            "/license.txt",
            "/wp-login.php",
            "/wp-cron.php",
            "/xmlrpc.php",
            "/wp-admin/admin-ajax.php",
            "/wp-admin/admin-post.php",
            "/wp-json/",
            "/wp-json/wp/v2/users",
            "/wp-json/wp/v2/posts",
        ],
        "params": [
            "p",
            "page_id",
            "cat",
            "search",
            "s",
            "author",
            "action",
            "nonce",
            "redirect_to",
            "log",
            "pwd",
        ],
        "wordlists": [
            "wordpress.fuzz.txt",
            "wp-plugins.fuzz.txt",
            "wp-themes.fuzz.txt",
            "urls-wordpress-3.3.1.txt",
        ],
    },

    "joomla": {
        "signals": {
            "headers": ["x-powered-by: php"],
            "body": [
                "/media/system/js/",
                "/components/com_",
                "/templates/",
                "joomla! - open source content management",
            ],
            "cookies": [],
            "probe_paths": ["/administrator/", "/robots.txt", "/index.php"],
        },
        "paths": [
            "/administrator/",
            "/components/",
            "/modules/",
            "/templates/",
            "/media/system/js/",
            "/cache/",
            "/components/com_content/",
            "/components/com_users/",
            "/components/com_media/",
            "/components/com_jce/",
            "/components/com_fields/",
            "/components/com_search/",
            "/templates/beez3/",
            "/templates/protostar/",
            "/templates/atomic/",
            "/configuration.php",
            "/htaccess.txt",
            "/robots.txt",
            "/index.php",
            "/administrator/index.php",
        ],
        "params": [
            "option",
            "view",
            "layout",
            "task",
            "id",
            "Itemid",
            "searchword",
            "catid",
            "lang",
            "username",
            "passwd",
            "return",
        ],
        "wordlists": [
            "joomla-plugins.fuzz.txt",
            "joomla-themes.fuzz.txt",
            "urls-joomla-3.0.3.txt",
        ],
    },

    "drupal": {
        "signals": {
            "headers": ["x-generator: drupal"],
            "body": [
                "/sites/default/files/",
                "/modules/contrib/",
                "window.drupalsettings",
                "drupal.settings",
            ],
            "cookies": [],
            "probe_paths": ["/CHANGELOG.txt", "/user/login", "/sites/default/files/"],
        },
        "paths": [
            "/sites/",
            "/sites/default/",
            "/sites/default/files/",
            "/sites/all/",
            "/sites/all/modules/",
            "/sites/all/themes/",
            "/includes/",
            "/modules/",
            "/sites/all/themes/zen/",
            "/sites/all/themes/omega/",
            "/sites/all/themes/bootstrap/",
            "/sites/default/settings.php",
            "/CHANGELOG.txt",
            "/cron.php",
            "/install.php",
            "/xmlrpc.php",
            "/index.php",
            "/authorize.php",
        ],
        "params": [
            "q",
            "node",
            "id",
            "destination",
            "name",
            "pass",
            "form_id",
            "form_token",
        ],
        "wordlists": [
            "drupal-themes.fuzz.txt",
            "urls-Drupal-7.20.txt",
        ],
    },

    "liferay": {
        "signals": {
            "headers": ["liferay-portal", "apache-coyote"],
            "body": [
                "liferay.currenturl",
                "/o/frontend-js-web/",
            ],
            "cookies": ["JSESSIONID"],
            "probe_paths": ["/api/jsonws", "/c/portal/login", "/o/frontend-js-web/"],
        },
        "paths": [
            "/o/",
            "/o/frontend-js-web/",
            "/html/themes/",
            "/html/portlet/",
            "/o/portal-search/",
            "/o/blogs-web/",
            "/o/document-library-web/",
            "/o/login-web/",
            "/api/jsonws",
            "/api/jsonws/invoke",
            "/api/secure/jsonws",
            "/c/portal/login",
            "/c/portal/layout",
        ],
        "params": [
            "p_p_id",
            "p_p_lifecycle",
            "p_p_state",
            "p_p_mode",
            "cmd",
            "parameterTypes",
            "-parameterExceptions",
            "_com_liferay_login_web_portlet_LoginPortlet_login",
            "_com_liferay_login_web_portlet_LoginPortlet_password",
        ],
        "wordlists": [
            "liferay_dxp_default_portlets.txt",
        ],
    },

    "sharepoint": {
        "signals": {
            "headers": [
                "microsoftsharepointteamservices",
                "x-sharepointhealthscore",
                "microsoft-iis",
            ],
            "body": [
                "/_layouts/15/",
                "/_api/web/",
                "sharepoint",
            ],
            "cookies": [
                "ASP.NET_SessionId",
                "__RequestVerificationToken",
            ],
            "probe_paths": [
                "/_api/web/",
                "/_layouts/15/About.aspx",
                "/_vti_bin/lists.asmx",
            ],
        },
        "paths": [
            "/_layouts/",
            "/_layouts/15/",
            "/_layouts/16/",
            "/_layouts/images/",
            "/sites/",
            "/_vti_bin/",
            "/_vti_pvt/",
            "/_vti_cnf/",
            "/forms/",
            "/_vti_bin/lists.asmx",
            "/_vti_bin/People.asmx",
            "/_vti_bin/search.asmx",
            "/_vti_bin/webpartpages.asmx",
            "/_vti_bin/usergroup.asmx",
            "/_api/web/",
            "/_layouts/15/About.aspx",
            "/_layouts/15/settings.aspx",
        ],
        "params": [
            "ID",
            "ListID",
            "ViewID",
            "Folder",
            "listName",
            "query",
            "viewName",
            "__VIEWSTATE",
            "__REQUESTDIGEST",
        ],
        "wordlists": [
            "Sharepoint.txt",
            "Sharepoint-Ennumeration.txt",
        ],
    },

    "moodle": {
        "signals": {
            "headers": [
                "x-powered-by: php",
            ],
            "body": [
                "moodle",
                "moodlesession",
                "/login/index.php",
                "/course/view.php",
                "/theme/yui_combo.php",
                "/lib/javascript.php",
                "/pluginfile.php",
                "/webservice/rest/server.php",
            ],
            "cookies": [
                "MoodleSession",
            ],
            "probe_paths": [
                "/login/index.php",
                "/course/index.php",
                "/admin/index.php",
                "/theme/yui_combo.php",
                "/lib/javascript.php",
                "/webservice/rest/server.php",
            ],
        },
        "paths": [
            "/login/index.php",
            "/course/index.php",
            "/course/view.php",
            "/admin/index.php",
            "/admin/settings.php",
            "/admin/search.php",
            "/admin/cron.php",
            "/user/profile.php",
            "/user/view.php",
            "/my/",
            "/calendar/view.php",
            "/grade/report/index.php",
            "/mod/forum/view.php",
            "/mod/quiz/view.php",
            "/mod/assign/view.php",
            "/mod/resource/view.php",
            "/mod/page/view.php",
            "/mod/url/view.php",
            "/mod/scorm/view.php",
            "/pluginfile.php",
            "/draftfile.php",
            "/webservice/rest/server.php",
            "/lib/ajax/service.php",
            "/theme/yui_combo.php",
            "/lib/javascript.php",
            "/theme/styles.php",
            "/message/index.php",
            "/badges/view.php",
            "/report/log/index.php",
        ],
        "params": [
            "id",
            "course",
            "courseid",
            "userid",
            "user",
            "page",
            "section",
            "search",
            "q",
            "sesskey",
            "returnurl",
            "redirect",
            "wstoken",
            "wsfunction",
            "moodlewsrestformat",
            "component",
            "contextid",
            "itemid",
            "filearea",
            "filepath",
            "filename",
        ],
        "wordlists": [
            "moodle.fuzz.txt",
        ],
    },
}